version: "3"

services:
  default-downloader:
    build: .
    container_name: default-downloader
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./logs
        target: /dd-data/logs

      - type: bind
        source: ./data
        target: /dd-data/data

      - type: volume
        source: dd-data
        target: /dd-data

  db:
    image: 'mongo:6.0'
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:27017" ]
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      mongod --quiet --logpath /dev/null                                # silence all mongodb image log output

volumes:
  mongodb:
  dd-data:
